%YAML:1.0

#camera calibration 
model_type: PINHOLE
camera_name: camera
image_width: 848
image_height: 480


  #Calibrated on 03/27/2024 distortion_coeffs: [0.003201493083132855, 0.003893292584573627, 0.0010782735616363269, 0.0008223459870432277]
distortion_parameters:
   k1: 0.003201493083132855
   k2: 0.003893292584573627
   p1: 0.0010782735616363269
   p2: 0.0008223459870432277

#Calibrated on 03/27/2024 intrinsics: [432.8806909447489, 434.0348592769353, 428.75210522005193, 242.00072426065566]
projection_parameters:
   fx: 432.8806909447489
   fy: 434.0348592769353
   cx: 428.75210522005193
   cy: 242.00072426065566